### ISSUE TITLE
패키지명 개선 제안

### ISSUE THREAD

**Issue by Jungwoo-An** [Flip-chat/server#1]
기존 패키지 명이 `com.wonchiyoung.filp` 로 사용되고 있는데, Java 프로젝트의 경우, 서버는 `com.flip.server`. 안드로이드는 `com.flip.android` 같은 표기를 사용해서 통일성을 만드는 건 어떨까요?

@wcyoung @smcake

**Comment by wcyoung** [comment]
@Jungwoo-An 안드로이드와 협의해서 com.flipchat 베이스로 정했습니다. 
f573d56ffb7178266b407b21f85ef5adfb8cccfb 에서 변경되었습니다.
